# -*- coding: utf-8 -*-
"""
/***************************************************************************
 capygis
                                 A QGIS plugin
 TP TICS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-22
        copyright            : (C) 2024 by LyA
        email                : asdasdsasdasdasdadassdsa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from .modules.analizador_datos.imports.instalaciones import verificar_e_instalar_librerias
verificar_e_instalar_librerias()

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load capygis class from file capygis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .capy_gis import capygis
    return capygis(iface)
